name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_versions
        with:
          config: ${{ github.workspace }}/.github/dependency_versions.yaml

      - name: Download dawn libs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          release_tag="${{ steps.read_versions.outputs['dawn'] }}"
          gh release download $release_tag -p dawn-static-linux64.tar.gz -R mandryskowski/dawn-build
          mkdir dawn-static-linux64
          tar -xvf dawn-static-linux64.tar.gz -C dawn-static-linux64 --strip-components=1
          echo "DAWN_BUILD_DIR=${{ github.workspace }}/dawn-static-linux64" >> $GITHUB_ENV

      - name: Run clippy
        run: cargo clippy --workspace --all-features -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: Swatinem/rust-cache@v2

      - uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_versions
        with:
          config: ${{ github.workspace }}/.github/dependency_versions.yaml

      - name: Download dawn libs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          release_tag="${{ steps.read_versions.outputs['dawn'] }}"
          gh release download $release_tag -p dawn-static-linux64.tar.gz -R mandryskowski/dawn-build
          mkdir dawn-static-linux64
          tar -xvf dawn-static-linux64.tar.gz -C dawn-static-linux64 --strip-components=1
          echo "DAWN_BUILD_DIR=${{ github.workspace }}/dawn-static-linux64" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get install -y libx11-dev

      - name: Run tests
        run: cargo test --workspace --all-features

  build_binaries:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - win64
          - macos64
          - linux64
          - android
        sanitizer:
          - none
          - asan-ubsan
        include:
          - target: win64
            os: ubuntu-latest
            rust-target: x86_64-pc-windows-msvc
            exe_suffix: .exe
          - target: macos64
            os: macos-latest
            rust-target: aarch64-apple-darwin
            exe_suffix: ""
          - target: linux64
            os: ubuntu-latest
            rust-target: x86_64-unknown-linux-gnu
            exe_suffix: ""
          - target: android
            os: ubuntu-latest
            rust-target: aarch64-linux-android
            exe_suffix: "" 

    env:
      ARTIFACT_SUFFIX: ${{ matrix.sanitizer == 'asan-ubsan' && '-asan-ubsan' || '' }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Android NDK
        id: setup-ndk
        if: matrix.target == 'android'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          
      - name: Install cargo-ndk
        if: matrix.target == 'android'
        run: cargo install cargo-ndk

      - name: Install rust toolchain
        run: rustup target add ${{ matrix.rust-target }}

      - name: Cache windows sdk
        id: cache-windows-sdk
        if: matrix.target == 'win64'
        uses: actions/cache@v4
        with:
          path: .xwin-cache
          key: xwin-cache

      - name: Download windows sdk
        if: matrix.target == 'win64' && steps.cache-windows-sdk.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/Jake-Shadle/xwin/releases/download/0.6.7/xwin-0.6.7-x86_64-unknown-linux-musl.tar.gz > $HOME/xwin.tar.gz
          tar -xvf $HOME/xwin.tar.gz -C $HOME
          sudo mv $HOME/xwin-0.6.7-x86_64-unknown-linux-musl/xwin /usr/bin
          xwin --accept-license splat --include-debug-libs

      - name: Install windows dependencies
        if: matrix.target == 'win64'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-19 clang-tools-19 llvm-19 lld-19 p7zip-full

      - name: Fetch Windows compiler-rt for ASan
        if: matrix.target == 'win64' && matrix.sanitizer == 'asan-ubsan'
        run: |
          curl -L "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.0/LLVM-19.1.0-win64.exe" -o llvm.exe
          7z x llvm.exe -o"$HOME/llvm-win"
          sudo mkdir -p /usr/lib/llvm-19/lib/clang/19/lib/windows
          find "$HOME/llvm-win" -type d -name "windows" | grep "lib/clang" | xargs -I {} sudo cp -r {}/. /usr/lib/llvm-19/lib/clang/19/lib/windows/

      - name: Install linux dependencies
        if: matrix.target == 'linux64'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-18 llvm-18 libx11-dev

      - uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_versions
        with:
          config: ${{ github.workspace }}/.github/dependency_versions.yaml

      - name: Download dawn libs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          release_tag="${{ steps.read_versions.outputs['dawn'] }}"
          dawn_folder="dawn-static-${{ matrix.target }}${{ env.ARTIFACT_SUFFIX }}"
          
          gh release download $release_tag -p ${dawn_folder}.tar.gz -R mandryskowski/dawn-build
          mkdir $dawn_folder
          tar -xvf ${dawn_folder}.tar.gz -C $dawn_folder --strip-components=1
          
          echo "DAWN_BUILD_DIR=${{ github.workspace }}/$dawn_folder" >> $GITHUB_ENV

      - name: Setup build environment
        shell: bash
        run: |
          if [ "${{ matrix.target }}" == "win64" ]; then
             echo "LLVM_NATIVE_TOOLCHAIN=/usr/lib/llvm-19" >> $GITHUB_ENV
             echo "XWIN_CACHE=${{ github.workspace }}/.xwin-cache/splat" >> $GITHUB_ENV
          fi

      - name: Build binaries
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CC: ${{ matrix.target == 'linux64' && 'clang-18' || 'clang' }}
          CXX: ${{ matrix.target == 'linux64' && 'clang++-18' || 'clang++' }}
        shell: bash
        run: |
          if [ "${{ matrix.target }}" == "android" ]; then
            export BINDGEN_EXTRA_CLANG_ARGS="--sysroot ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot --target=aarch64-linux-android"
          fi
          
          BUILD_ARGS="--target ${{ matrix.rust-target }}"
          
          if [ "${{ matrix.sanitizer }}" == "asan-ubsan" ]; then
            BUILD_ARGS="$BUILD_ARGS --asan --ubsan"
          fi
          
          ./build.py harness $BUILD_ARGS
          ./build.py wgslsmith $BUILD_ARGS

      - name: Stage artifacts
        shell: bash
        run: |
          mkdir -p staging_harness
          mkdir -p staging_wgslsmith
          
          if [ "${{ matrix.target }}" == "android" ]; then
            cp target/${{ matrix.rust-target }}/release/wgslsmith-harness staging_harness/
            cp target/${{ matrix.rust-target }}/release/wgslsmith staging_wgslsmith/
            cp ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so staging_harness/
          else
            cp cross-target/${{ matrix.rust-target }}/release/wgslsmith-harness${{ matrix.exe_suffix }} staging_harness/
            cp cross-target/${{ matrix.rust-target }}/release/wgslsmith${{ matrix.exe_suffix }} staging_wgslsmith/
          fi
          
          # If Windows + ASan, ship the dynamic compiler-rt library next to the executable
          if [ "${{ matrix.target }}" == "win64" ] && [ "${{ matrix.sanitizer }}" == "asan-ubsan" ]; then
            cp /usr/lib/llvm-19/lib/clang/19/lib/windows/clang_rt.asan_dynamic-x86_64.dll staging_harness/
            cp /usr/lib/llvm-19/lib/clang/19/lib/windows/clang_rt.asan_dynamic-x86_64.dll staging_wgslsmith/
          fi

      - name: Upload harness artifact
        uses: actions/upload-artifact@v4
        with:
          name: harness-${{ matrix.target }}${{ env.ARTIFACT_SUFFIX }}
          path: staging_harness/*

      - name: Upload fuzzer artifact
        uses: actions/upload-artifact@v4
        with:
          name: wgslsmith-${{ matrix.target }}${{ env.ARTIFACT_SUFFIX }}
          path: staging_wgslsmith/*

  test_harness:
    runs-on: ${{ matrix.os }}
    needs: build_binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022  # windows-latest breaks ASan
          - ubuntu-latest
          - macos-latest
        sanitizer:
          - none
          - asan-ubsan
        include:
          - os: windows-2022
            artifact: win64
          - os: ubuntu-latest
            artifact: linux64
          - os: macos-latest
            artifact: macos64

    env:
      ARTIFACT_SUFFIX: ${{ matrix.sanitizer == 'asan-ubsan' && '-asan-ubsan' || '' }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download swiftshader
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          release_tag=`gh release view --json tagName -q '.tagName' -R mandryskowski/swiftshader-build`
          gh release download $release_tag -p swiftshader-${{ matrix.artifact }}.tar.gz -R mandryskowski/swiftshader-build
          tar -xvf swiftshader-${{ matrix.artifact }}.tar.gz

      - name: Download harness
        uses: actions/download-artifact@v4
        with:
          name: harness-${{ matrix.artifact }}${{ env.ARTIFACT_SUFFIX }}
          path: harness-staging

      - name: Copy dependencies (Windows)
        if: matrix.os == 'windows-2022'
        shell: bash
        run: |
          cp swiftshader-${{ matrix.artifact }}/vulkan-1.dll harness-staging/
          cp tools/dxcompiler.dll harness-staging/
          cp tools/dxil.dll harness-staging/

      - name: Install Vulkan SDK (macOS)
        if: matrix.os == 'macos-latest'
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          version: latest
          install_runtime: true
          cache: true

      - name: Run test shaders
        env:
          VK_ICD_FILENAMES: ${{ github.workspace }}/swiftshader-${{ matrix.artifact }}/vk_swiftshader_icd.json
          ASAN_OPTIONS: "detect_odr_violation=0:detect_leaks=0:suppressions=tools/asan_suppressions.txt"
        shell: bash
        run: |
          chmod +x ./harness-staging/wgslsmith-harness
          
          mkdir -p tools
          touch tools/asan_suppressions.txt
          
          ./harness-staging/wgslsmith-harness run crates/harness/test.wgsl crates/harness/test.json
